services:
  console.container_debug:
    class: WP\Console\Command\ContainerDebugCommand
    tags:
      - { name: wordpress.command }
  console.shortcode_debug:
      class: WP\Console\Command\ShortcodeDebugCommand
      arguments: ['@console.site']
      tags:
        - { name: wordpress.command }
